// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import (
	"database/sql"
)

type Log struct {
	Lift          sql.NullString  `json:"lift"`
	Weight        sql.NullInt32   `json:"weight"`
	Reps          sql.NullInt32   `json:"reps"`
	CalculatedMax sql.NullFloat64 `json:"calculatedMax"`
}

type Max struct {
	Lift        sql.NullString `json:"lift"`
	Onerepmax   sql.NullInt32  `json:"onerepmax"`
	Trainingmax sql.NullInt32  `json:"trainingmax"`
}
